version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: school1
       MYSQL_DATABASE: webserver
       MYSQL_USER: oracle
       MYSQL_PASSWORD: school1
     networks:
       net:
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: oracle
       WORDPRESS_DB_PASSWORD: school1
       WORDPRESS_DB_NAME: webserver
     networks:
         net:
volumes:
    db_data: 

networks:
   net:
